FROM nginx:1.27-alpine
RUN rm -f /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/conf.d /etc/nginx/conf.d
RUN mkdir -p /etc/nginx/certs \
 && apk add --no-cache openssl \
 && openssl req -x509 -nodes -newkey rsa:2048 -days 365 \
 -keyout /etc/nginx/certs/privkey.pem \
 -out /etc/nginx/certs/fullchain.pem \
 -subj "/CN=localhost"
EXPOSE 80 443
